services:
    marttiphpbb.showtopicsubscribers.listener:
        class: marttiphpbb\showtopicsubscribers\event\listener
        arguments:
            - @auth
            - @config
            - @controller.helper
            - %core.php_ext%
            - @template
            - @user
        tags:
            - { name: event.listener }
