services:
    marttiphpbb.showtopicsubscribers.listener:
        class: marttiphpbb\showtopicsubscribers\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '@marttiphpbb.showtopicsubscribers.topic_subscribers'
        tags:
            - { name: event.listener }

    marttiphpbb.showtopicsubscribers.topic_subscribers:
        class: marttiphpbb\showtopicsubscribers\service\topic_subscribers
        arguments:
            - '@dbal.conn'
            - '%tables.topics_watch%'
            - '%tables.users%'